name: minecraft-callback
version: 1.0.1
api-version: 1.20
website: github.com/estaria-world
author: MrManHD

main: world.estaria.minecraft.callback.plugin.paper.LimboPlugin

depend:
  - spigot-dependency-loader